### PR TITLE
Fix UTF8 pasting on wayland

### PR DESCRIPTION
**Pull request by danog**
Copying and pasting UTF-8 characters from any app to tdesktop on wayland pastes a JSON-encoded version of the character (à => \u00e0).
This patch fixes https://github.com/telegramdesktop/tdesktop/issues/8628.

### CODE REVIEW

**Comment by ilya-fedin** [comment]
there are already a patch with 0029 number

**Comment by danog** [comment]
Hmm, where though? I don't see it in this repo

**Comment by ilya-fedin** [comment]
> Hmm, where though? I don't see it in this repo

You have very poor eyesight
image

**Comment by danog** [comment]
I saw https://github.com/desktop-app/patches/blob/master/qtbase_5_12_8/0029-old-freetype-compatibility.patch, but it has nothing to do with wayland clipboard behavior.

**Comment by ilya-fedin** [comment]
Two patches can't have the same number

**Comment by danog** [comment]
Oh that's what you meant, I completely missed that for some reason, sorry!

**Comment by ilya-fedin** [comment]
You can add `Fixes https://github.com/telegramdesktop/tdesktop/issues/8628` to the first post to link the PR to the issue and make it automatically closed on merge

**Comment by danog** [comment]
Done.

**Pull request merged**
