### PR TITLE
Add ability to set custom margins for window shadows on Wayland

### PR DESCRIPTION
**Pull request by ilya-fedin**

### CODE REVIEW

**Comment by grulja** [comment]
Hi, I have interest in this. I was looking into implementing support for shadows to qtwayland myself. Do you think this is something you can try to upstream?

**Comment by ilya-fedin** [comment]
I'm not sure how really it's upstreamable given that it feels like a hack since it requires changes to all shell integrations

**Comment by ilya-fedin** [comment]
I wonder why they using QWindow::frameGeometry instead of QWaylandWindow::windowContentGeometry... Is there a reason like it's not valid on configure event or it's just it appeared after the code was written? Using windowContentGeometry probably will remove the feeling of a hack... But QWindow::frameGeometry uses QHighDpi::fromNativeWindowGeometry under the hood, that adds additional feeling that they aren't replaceable (and I don't use QHighDpi::fromNativePixels for my margins, so probably they will work incorrectly at HiDPI scaling) :(

**Comment by ilya-fedin** [comment]
Oh, it uses QPlatformWindow::windowFrameGeometry now
https://github.com/qt/qtwayland/commit/8cb1b07aea12d50b4fecc45c903705dfd368022a#diff-0a59ca1a6a0e50daa8dbc907bf4dea591a411bfdafefdf244e2d0bad3c7d7263

So QWaylandWindow::windowContentGeometry should probably fit...

**Comment by grulja** [comment]
> I'm not sure how really it's upstreamable given that it feels like a hack since it requires changes to all shell integrations

Not sure it's upstreamable in current form (because of the custom property), I think it would make sense to add some API for shadows so decoration plugins can override it and set accordingly. Using a custom property will make it hard to discover.

**Comment by ilya-fedin** [comment]
> I think it would make sense to add some API for shadows so decoration plugins can override it and set accordingly.

But how application developers can reach such API? Windows QPA, for instance, has WindowsCustomMargins.

**Comment by grulja** [comment]
I think I misunderstood what this patch is about. 

Your usecase is that you want to paint shadows in the app itself, not through QAbstractDecorationPlugin, is that correct? In that case if I get it right you have no option to set frameMargins().

My usecase is that I work on a decoration plugin, where I can set margins(), but I use it currently for borders and window title part. I wanted to add option to specify shadows additionally in order to hide them when window gets maximized, while keeping margins used for the rest (border and window title part).

**Comment by ilya-fedin** [comment]
> Your usecase is that you want to paint shadows in the app itself, not through QAbstractDecorationPlugin, is that correct?

Yeah.

> In that case if I get it right you have no option to set frameMargins().

Yeah, unfortunately, while it is possible to set custom margins via libxcb on X11 and via WindowsCustomMargins on Windows. This patch adds a way to do that on Wayland as well.

**Pull request merged**
